version: "3"
services:
  redis:
    container_name: redis-ghibili
    build:
      context: /
      dockerfile: /home/mani/Documents/ghibili/be/.redis.Dockerfile
    volumes:
      - "/data:/data"
    ports:
      - "6380:6380"
